apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: argocd
  name: argocd-server
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.trifolium.fleeingsunlight.dev`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
  tls:
    certResolver: myresolver
