apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/FleeingSunlight/trifolium.git
    targetRevision: HEAD
    path: hello-world/envs/dev
